In [1]:
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 17 16:07:38 2020

@author: DHRUV
"""


import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""
HW1 b (iii)

"""

df=pd.read_csv('column_2C.dat', sep='\s+',header=None)
df.columns = ['a','b','c','d','e','f','O']
print(df)
df.loc[(df.O == 'AB'),'O']=1            
df.loc[(df.O == 'NO'),'O']=0            
print(df)
column_names = ['a','b','c','d','e','f','O']
i_dtest = np.arange(100)
i_dtraining = np.arange(210)
df_test = pd.DataFrame(columns=column_names, index=i_dtest)
df_training = pd.DataFrame(columns=column_names,index=i_dtraining)
print(df_test)
print(df_training)
r=np.arange(140)
s=np.arange(start=140,stop=210)

for i in r:
    df_training.loc[i]=df.loc[i]

    
for j in s:
    df_training.loc[j]=df.loc[j+70]

print(df_training)

u=np.arange(70)
v=np.arange(start=70,stop=100)

for k in u:
    df_test.loc[k]=df.loc[k+140]

for l in v:
    df_test.loc[l]=df.loc[l+210]

print(df_test)

df.to_csv('Data.csv')
df_training.to_csv('TrainingData.csv')
df_test.to_csv('TestData.csv')


"""
Code Explanation

We've read the data file first, converted the column headers into (a,b,c,d,e,f,O) and 
printed it.

Then we've converted the AB entry in O (Output) to 1 (Class 1, Numeric)
And the NO in O into 0 (Class 0, Numeric)

Then we've defined empty dataframes df_test and df_training to copy appropriate rows from
original dataframe df

Their column headers are same as df and row indices are:
    
df_training : 0 to 209 (210 rows)
df_test : 0 to 99 (100 rows)

TO COPY rows of df to df_training: To accomplish this to numpy arrays r and s are defined.
Over two FOR loops, r copies the first 140 rows of df to df_training and then for its last 
70 rows (from 140 to 209), s copies df rows from 210 to 279 index (corresponding to first
70 class 0 entries) into df_training. This completes formation of Training Data.

TO COPY rows of df to df_test: Similar method using u and v and two FOR loops. We copy 
remaining class 1 and class 0 data into df_test. This completes formation of Test Data.

Finally we export df, df_training and df_test to Data, TrainingData, TestData .csv files
for use in subsequent parts of HW1

"""

         a      b      c      d       e      f   O
0    63.03  22.55  39.61  40.48   98.67  -0.25  AB
1    39.06  10.06  25.02  29.00  114.41   4.56  AB
2    68.83  22.22  50.09  46.61  105.99  -3.53  AB
3    69.30  24.65  44.31  44.64  101.87  11.21  AB
4    49.71   9.65  28.32  40.06  108.17   7.92  AB
..     ...    ...    ...    ...     ...    ...  ..
305  47.90  13.62  36.00  34.29  117.45  -4.25  NO
306  53.94  20.72  29.22  33.22  114.37  -0.42  NO
307  61.45  22.69  46.17  38.75  125.67  -2.71  NO
308  45.25   8.69  41.58  36.56  118.55   0.21  NO
309  33.84   5.07  36.64  28.77  123.95  -0.20  NO

[310 rows x 7 columns]
         a      b      c      d       e      f  O
0    63.03  22.55  39.61  40.48   98.67  -0.25  1
1    39.06  10.06  25.02  29.00  114.41   4.56  1
2    68.83  22.22  50.09  46.61  105.99  -3.53  1
3    69.30  24.65  44.31  44.64  101.87  11.21  1
4    49.71   9.65  28.32  40.06  108.17   7.92  1
..     ...    ...    ...    ...     ...    ... ..
305  47.90  13.62  36.00  34.29  117.45  -4.25  0
306  53.94  20.72  29.22  33.22  114.37  -0.42  0
307  61.45  22.69  46.17  38.75  125.67  -2.71  0
308  45.25   8.69  41.58  36.56  118.55   0.21  0
309  33.84   5.07  36.64  28.77  123.95  -0.20  0

[310 rows x 7 columns]
      a    b    c    d    e    f    O
0   NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN  NaN  NaN  NaN
..  ...  ...  ...  ...  ...  ...  ...
95  NaN  NaN  NaN  NaN  NaN  NaN  NaN
96  NaN  NaN  NaN  NaN  NaN  NaN  NaN
97  NaN  NaN  NaN  NaN  NaN  NaN  NaN
98  NaN  NaN  NaN  NaN  NaN  NaN  NaN
99  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[100 rows x 7 columns]
       a    b    c    d    e    f    O
0    NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    NaN  NaN  NaN  NaN  NaN  NaN  NaN
4    NaN  NaN  NaN  NaN  NaN  NaN  NaN
..   ...  ...  ...  ...  ...  ...  ...
205  NaN  NaN  NaN  NaN  NaN  NaN  NaN
206  NaN  NaN  NaN  NaN  NaN  NaN  NaN
207  NaN  NaN  NaN  NaN  NaN  NaN  NaN
208  NaN  NaN  NaN  NaN  NaN  NaN  NaN
209  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[210 rows x 7 columns]
         a      b      c      d       e      f  O
0    63.03  22.55  39.61  40.48   98.67  -0.25  1
1    39.06  10.06  25.02     29  114.41   4.56  1
2    68.83  22.22  50.09  46.61  105.99  -3.53  1
3     69.3  24.65  44.31  44.64  101.87  11.21  1
4    49.71   9.65  28.32  40.06  108.17   7.92  1
..     ...    ...    ...    ...     ...    ... ..
205  67.29  16.72     51  50.57  137.59   4.96  0
206  51.33  13.63  33.26  37.69  131.31   1.79  0
207  65.76  13.21     44  52.55  129.39  -1.98  0
208  40.41  -1.33  30.98  41.74  119.34  -6.17  0
209   48.8  18.02     52  30.78  139.15  10.44  0

[210 rows x 7 columns]
        a      b       c      d       e       f  O
0   69.56   15.4   74.44  54.16  105.07    29.7  1
1    89.5   48.9      72   40.6  134.63  118.35  1
2   85.29  18.28  100.74  67.01  110.66   58.88  1
3   60.63   20.6   64.54  40.03  117.23  104.86  1
4   60.04  14.31   58.04  45.73  105.13   30.41  1
..    ...    ...     ...    ...     ...     ... ..
95   47.9  13.62      36  34.29  117.45   -4.25  0
96  53.94  20.72   29.22  33.22  114.37   -0.42  0
97  61.45  22.69   46.17  38.75  125.67   -2.71  0
98  45.25   8.69   41.58  36.56  118.55    0.21  0
99  33.84   5.07   36.64  28.77  123.95    -0.2  0

[100 rows x 7 columns]

"\nCode Explanation\n\nWe've read the data file first, converted the column headers into (a,b,c,d,e,f,O) and \nprinted it.\n\nThen we've converted the AB entry in O (Output) to 1 (Class 1, Numeric)\nAnd the NO in O into 0 (Class 0, Numeric)\n\nThen we've defined empty dataframes df_test and df_training to copy appropriate rows from\noriginal dataframe df\n\nTheir column headers are same as df and row indices are:\n    \ndf_training : 0 to 209 (210 rows)\ndf_test : 0 to 99 (100 rows)\n\nTO COPY rows of df to df_training: To accomplish this to numpy arrays r and s are defined.\nOver two FOR loops, r copies the first 140 rows of df to df_training and then for its last \n70 rows (from 140 to 209), s copies df rows from 210 to 279 index (corresponding to first\n70 class 0 entries) into df_training. This completes formation of Training Data.\n\nTO COPY rows of df to df_test: Similar method using u and v and two FOR loops. We copy \nremaining class 1 and class 0 data into df_test. This completes formation of Test Data.\n\nFinally we export df, df_training and df_test to Data, TrainingData, TestData .csv files\nfor use in subsequent parts of HW1\n\n"